kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm-external-haproxy
  namespace: fleet-default
spec:
  repo: https://github.com/openkubeio/rancher-fleet-examples
  paths:
  - multi-cluster/helm-external-haproxy
  targetNamespace: default
  targets:
    - clusterGroup: dev-airflow
